window.CONDOS = [
  {
    "unit": "1001",
    "floor": 1,
    "occupancy": null,
    "permit": null,
    "permitLabel": null,
    "contact": null,
    "phone": null,
    "operator": null,
    "verified": false,
    "notes": "Unit number observed on-site. Rental, occupancy, and registration details have not yet been captured.",
    "operatorUrl": null
  },
  {
    "unit": "1002",
    "floor": 1,
    "occupancy": 8,
    "permit": "200105610",
    "permitLabel": "STR #",
    "contact": "Port Aransas Escapes",
    "phone": "361-749-3591",
    "operator": "Port Aransas Escapes",
    "verified": true,
    "notes": "Posted registration sign photographed on-site.",
    "operatorUrl": "https://www.portaescapes.com/"
  },
  {
    "unit": "1003",
    "floor": 1,
    "occupancy": 6,
    "permit": "200105612",
    "permitLabel": "STR #",
    "contact": "Sand Key Realty",
    "phone": "361-749-4255",
    "operator": "Sand Key Realty",
    "verified": true,
    "notes": "Posted registration sign photographed on-site.",
    "operatorUrl": "https://www.sandkeyvacationrentals.com/"
  },
  {
    "unit": "1004",
    "floor": 1,
    "occupancy": 6,
    "permit": "200105614",
    "permitLabel": "STR #",
    "contact": "Starkey Properties",
    "phone": "361-749-3591",
    "operator": "Starkey Properties",
    "verified": true,
    "notes": "Posted registration sign photographed on-site.",
    "operatorUrl": null
  },
  {
    "unit": "1006",
    "floor": 1,
    "occupancy": 6,
    "permit": "200105618",
    "permitLabel": "STR #",
    "contact": "Silver Sands Vacation Rentals",
    "phone": "361-749-2600",
    "operator": "Silver Sands Vacation Rentals",
    "verified": true,
    "notes": "Posted registration sign photographed on-site.",
    "operatorUrl": null
  },
  {
    "unit": "1007",
    "floor": 1,
    "occupancy": 6,
    "permit": "200105620",
    "permitLabel": "STR #",
    "contact": "Sand Key Realty",
    "phone": "361-749-4255",
    "operator": "Sand Key Realty",
    "verified": true,
    "notes": "Posted registration sign photographed on-site.",
    "operatorUrl": "https://www.sandkeyvacationrentals.com/"
  },
  {
    "unit": "2001",
    "floor": 2,
    "occupancy": null,
    "permit": null,
    "permitLabel": null,
    "contact": null,
    "phone": null,
    "operator": null,
    "verified": false,
    "notes": "Unit number observed on-site. Rental, occupancy, and registration details have not yet been captured.",
    "operatorUrl": null
  },
  {
    "unit": "2002",
    "floor": 2,
    "occupancy": 8,
    "permit": "200105630",
    "permitLabel": "STR #",
    "contact": "Zenaida Castillo",
    "phone": "361-389-4507",
    "operator": "Owner/contact",
    "verified": true,
    "notes": "Posted registration sign photographed on-site.",
    "operatorUrl": null
  },
  {
    "unit": "2003",
    "floor": 2,
    "occupancy": 6,
    "permit": "200105633",
    "permitLabel": "STR #",
    "contact": "Port A Retreat",
    "phone": "361-649-2776",
    "operator": "Port A Retreat",
    "verified": true,
    "notes": "Posted registration sign photographed on-site.",
    "operatorUrl": null
  },
  {
    "unit": "2004",
    "floor": 2,
    "occupancy": null,
    "permit": null,
    "permitLabel": null,
    "contact": null,
    "phone": null,
    "operator": null,
    "verified": false,
    "notes": "Unit number observed on-site. Rental, occupancy, and registration details have not yet been captured.",
    "operatorUrl": null
  },
  {
    "unit": "2005",
    "floor": 2,
    "occupancy": 8,
    "permit": "011956",
    "permitLabel": "Registration No.",
    "contact": "Lydia Rickard",
    "phone": "817-988-1378",
    "operator": "Direct contact",
    "verified": true,
    "notes": "Posted sign lists Lydia Rickard as the contact person and uses Registration No. 011956.",
    "operatorUrl": null
  },
  {
    "unit": "2008",
    "floor": 2,
    "occupancy": 6,
    "permit": "200105642",
    "permitLabel": "STR #",
    "contact": "Silver Sands Vacation Rentals",
    "phone": "361-749-2600",
    "operator": "Silver Sands Vacation Rentals",
    "verified": true,
    "notes": "Posted registration sign photographed through reflective glass; the STR number should be confirmed when booking.",
    "operatorUrl": null
  },
  {
    "unit": "2009",
    "floor": 2,
    "occupancy": 8,
    "permit": "200105644",
    "permitLabel": "STR #",
    "contact": "Sand Key Realty",
    "phone": "361-749-4255",
    "operator": "Sand Key Realty",
    "verified": true,
    "notes": "Posted registration sign photographed on-site.",
    "operatorUrl": "https://www.sandkeyvacationrentals.com/"
  },
  {
    "unit": "3008",
    "floor": 3,
    "occupancy": null,
    "permit": null,
    "permitLabel": null,
    "contact": "Port Aransas Escapes",
    "phone": null,
    "operator": "Port Aransas Escapes",
    "verified": false,
    "bookingUrl": "https://www.portaescapes.com/rentals/grand-caribbean-gc3008is",
    "notes": "Direct rental listing supplied for GC3008; on-site registration details have not yet been captured.",
    "operatorUrl": "https://www.portaescapes.com/"
  },
  {
    "unit": "3009",
    "floor": 3,
    "occupancy": null,
    "permit": null,
    "permitLabel": null,
    "contact": null,
    "phone": null,
    "operator": null,
    "verified": false,
    "notes": "Unit number observed on-site. Rental, occupancy, and registration details have not yet been captured.",
    "operatorUrl": null
  },
  {
    "unit": "3010",
    "floor": 3,
    "occupancy": 8,
    "permit": "200105666",
    "permitLabel": "STR #",
    "contact": "Starkey Properties",
    "phone": "361-749-3591",
    "operator": "Starkey Properties",
    "verified": true,
    "notes": "Posted registration sign photographed on-site.",
    "operatorUrl": null
  },
  {
    "unit": "4009",
    "floor": 4,
    "occupancy": null,
    "permit": null,
    "permitLabel": null,
    "contact": null,
    "phone": null,
    "operator": null,
    "verified": false,
    "notes": "Unit number observed on-site. Rental, occupancy, and registration details have not yet been captured.",
    "operatorUrl": null
  },
  {
    "unit": "4010",
    "floor": 4,
    "occupancy": null,
    "permit": null,
    "permitLabel": null,
    "contact": null,
    "phone": null,
    "operator": null,
    "verified": false,
    "notes": "Unit number observed on-site. Rental, occupancy, and registration details have not yet been captured.",
    "operatorUrl": null
  }
];
